version: '3'
services:
    aind:
      image: 'aind/aind'
      privileged: true
      tty: true
      environment:
        - WEBMODE=1
      ports:
        - '5900:5900'
        - '8080:8080'
      volumes:
        - '/lib/modules:/lib/modules:ro'
        - 'dot-vnc:/home/user/.vnc'
volumes:
  dot-vnc:
